# Generated by Django 2.0.9 on 2018-10-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titill', models.CharField(max_length=255, verbose_name='Bókartitill')),
                ('stutt_lysing', models.TextField(blank=True, verbose_name='Stutt lýsing')),
                ('long_lysing', models.TextField(verbose_name='Löng lýsing')),
                ('verd', models.PositiveIntegerField(verbose_name='Verð')),
            ],
            options={
                'verbose_name': 'Bók',
                'verbose_name_plural': 'Bækur',
                'ordering': ('titill',),
            },
        ),
        migrations.CreateModel(
            name='Hofundur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornafn', models.CharField(max_length=255, verbose_name='Fornafn')),
                ('eftirnafn', models.CharField(max_length=255, verbose_name='Eftirnafn')),
            ],
            options={
                'verbose_name': 'Höfundur',
                'verbose_name_plural': 'Höfundar',
                'ordering': ('fornafn', 'eftirnafn'),
            },
        ),
    ]
