# Generated by Django 2.0.9 on 2018-10-09 19:20

import bokaforlag.baekur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titill', models.CharField(max_length=255, verbose_name='Bókartitill')),
                ('stutt_lysing', models.TextField(blank=True, verbose_name='Stutt lýsing')),
                ('long_lysing', models.TextField(help_text='Notaðu Markdown til að skrifa lýsinguna: https://en.wikipedia.org/wiki/Markdown. Tvö bil til að skipta yfir í næstu línu.', verbose_name='Löng lýsing')),
                ('verd', models.PositiveIntegerField(verbose_name='Verð')),
                ('syna_verd', models.BooleanField(default=True, verbose_name='Sýna verð')),
                ('mynd', models.ImageField(blank=True, upload_to=bokaforlag.baekur.models.bokarmynd_path)),
            ],
            options={
                'verbose_name': 'Bók',
                'verbose_name_plural': 'Bækur',
                'ordering': ('titill',),
            },
        ),
        migrations.CreateModel(
            name='Hofundur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nafn', models.CharField(max_length=255, verbose_name='nafn')),
            ],
            options={
                'verbose_name': 'Höfundur',
                'verbose_name_plural': 'Höfundar',
                'ordering': ('nafn',),
            },
        ),
        migrations.AddField(
            model_name='bok',
            name='hofundur',
            field=models.ManyToManyField(related_name='baekur', to='baekur.Hofundur', verbose_name='Höfundur'),
        ),
    ]
