# Generated by Django 2.0.9 on 2018-10-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok',
            name='hofundur',
            field=models.ManyToManyField(related_name='hofundar', to='baekur.Hofundur'),
        ),
    ]
