# Generated by Django 2.0.9 on 2018-10-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0002_bok_hofundur'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok',
            name='mynd',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='bok',
            name='hofundur',
            field=models.ManyToManyField(related_name='baekur', to='baekur.Hofundur'),
        ),
    ]
