# Generated by Django 2.0.9 on 2018-10-06 21:53

import bokaforlag.baekur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0003_auto_20181005_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bok',
            name='mynd',
            field=models.ImageField(blank=True, upload_to=bokaforlag.baekur.models.bokarmynd_path),
        ),
    ]
