# Generated by Django 2.0.9 on 2018-10-07 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0004_auto_20181006_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hofundur',
            options={'ordering': ('nafn',), 'verbose_name': 'Höfundur', 'verbose_name_plural': 'Höfundar'},
        ),
        migrations.RemoveField(
            model_name='hofundur',
            name='eftirnafn',
        ),
        migrations.RemoveField(
            model_name='hofundur',
            name='fornafn',
        ),
        migrations.AddField(
            model_name='hofundur',
            name='nafn',
            field=models.CharField(default='x', max_length=255, verbose_name='nafn'),
            preserve_default=False,
        ),
    ]
