# Generated by Django 2.0.9 on 2018-10-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0004_auto_20181008_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bok',
            name='hofundur',
            field=models.ManyToManyField(related_name='baekur', to='baekur.Hofundur', verbose_name='Höfundur'),
        ),
    ]
