# Generated by Django 2.0.9 on 2019-01-15 00:33

import bokaforlag.baekur.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0005_auto_20181011_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok',
            name='afslattur',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Afsláttur í kr.'),
        ),
        migrations.AlterField(
            model_name='bok',
            name='mynd',
            field=models.ImageField(blank=True, upload_to=bokaforlag.baekur.models.bokarmynd_path, verbose_name='Mynd'),
        ),
    ]
