# Generated by Django 2.0.9 on 2018-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0005_auto_20181007_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok',
            name='syna_verd',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bok',
            name='hofundur',
            field=models.ManyToManyField(related_name='baekur', to='baekur.Hofundur', verbose_name='Höfundur'),
        ),
    ]
