# Generated by Django 2.0.9 on 2019-01-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0006_auto_20190115_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bok',
            name='afslattur',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Afsláttur í kr.'),
        ),
    ]
