# Generated by Django 2.0.9 on 2019-01-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baekur', '0007_auto_20190115_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='bok',
            name='afsl_byrjar',
            field=models.DateField(blank=True, null=True, verbose_name='Afsláttur byrjar'),
        ),
        migrations.AddField(
            model_name='bok',
            name='afsl_endar',
            field=models.DateField(blank=True, null=True, verbose_name='Afsláttur endar'),
        ),
    ]
