# Generated by Django 2.0.9 on 2018-10-30 23:36

import bokaforlag.myndir.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mynd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titill', models.CharField(max_length=128)),
                ('mynd', models.ImageField(blank=True, upload_to=bokaforlag.myndir.models.mynd_path)),
            ],
            options={
                'verbose_name': 'Mynd',
                'verbose_name_plural': 'Myndir',
                'ordering': ('id',),
            },
        ),
    ]
