# Generated by Django 2.0.9 on 2018-10-30 23:38

import bokaforlag.myndir.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myndir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynd',
            name='mynd',
            field=models.ImageField(upload_to=bokaforlag.myndir.models.mynd_path),
        ),
    ]
