# Generated by Django 2.0.9 on 2018-10-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frett',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titill', models.CharField(max_length=128, verbose_name='Titill')),
                ('texti', models.CharField(max_length=2000, verbose_name='Texti')),
                ('tengill', models.URLField(max_length=128, verbose_name='Tengill')),
                ('tengill_texti', models.CharField(max_length=128, verbose_name='Texti á tengli')),
            ],
            options={
                'verbose_name': 'Frétt',
                'verbose_name_plural': 'Fréttir',
                'ordering': ('id',),
            },
        ),
    ]
