# Generated by Django 2.0.9 on 2018-10-30 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frettir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frett',
            name='tengill',
            field=models.URLField(blank=True, max_length=128, null=True, verbose_name='Tengill'),
        ),
        migrations.AlterField(
            model_name='frett',
            name='tengill_texti',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Texti á tengli'),
        ),
    ]
