# Generated by Django 2.0.9 on 2018-10-07 14:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buin_til', models.DateTimeField(auto_now_add=True)),
                ('stada', models.CharField(choices=[('AFGREIDD', 'Afgreidd'), ('EKKI_AFGREIDD', 'Ekki afgreidd')], default='EKKI_AFGREIDD', max_length=255)),
                ('vidskiptavinur', models.CharField(max_length=255)),
                ('magn', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'verbose_name': 'Pöntun',
                'verbose_name_plural': 'Pantanir',
                'ordering': ('-buin_til',),
            },
        ),
    ]
