# Generated by Django 2.0.9 on 2018-10-09 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pontun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buin_til', models.DateTimeField(auto_now_add=True, verbose_name='Búin til')),
                ('uppfaerd', models.DateTimeField(auto_now=True, verbose_name='Uppfærð')),
                ('stada', models.CharField(choices=[('EKKI_AFGREIDD', 'Ekki afgreidd'), ('INNHEIMTA_SEND', 'Innheimta send í heimabanka'), ('AFGREIDD', 'Afgreidd')], default='EKKI_AFGREIDD', max_length=255, verbose_name='Staða')),
                ('nafn', models.CharField(max_length=255, verbose_name='Nafn')),
                ('netfang', models.EmailField(max_length=254, verbose_name='Netfang')),
                ('kennitala', models.CharField(help_text='Skrifaðu kennitöluna á forminu XXXXXX-XXXX.', max_length=255, validators=[django.core.validators.RegexValidator('^\\d{6}-\\d{4}$')], verbose_name='Kennitala')),
                ('heimilisfang', models.CharField(max_length=255, verbose_name='Heimilisfang')),
                ('postnumer', models.CharField(max_length=255, verbose_name='Póstnúmer')),
                ('stadur', models.CharField(max_length=255, verbose_name='Staður')),
                ('land', models.CharField(max_length=255, verbose_name='Land')),
                ('simanumer', models.CharField(max_length=255, verbose_name='Símanúmer')),
                ('athugasemd', models.TextField(blank=True, verbose_name='Athugasemd')),
                ('bok', models.CharField(max_length=255, verbose_name='Bók')),
                ('magn', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Magn')),
            ],
            options={
                'verbose_name': 'Pöntun',
                'verbose_name_plural': 'Pantanir',
                'ordering': ('-buin_til',),
            },
        ),
    ]
