# Generated by Django 2.0.9 on 2018-10-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontun',
            name='uppfaerd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='stada',
            field=models.CharField(choices=[('EKKI_AFGREIDD', 'Ekki afgreidd'), ('INNHEIMTA_SEND', 'Innheimta send í heimabanka'), ('AFGREIDD', 'Afgreidd')], default='EKKI_AFGREIDD', max_length=255),
        ),
    ]
