# Generated by Django 2.0.9 on 2018-10-09 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontun',
            name='bok',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baekur', to='baekur.Bok', verbose_name='Bækur'),
        ),
    ]
