# Generated by Django 2.0.9 on 2018-10-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0002_auto_20181007_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontun',
            name='athugasemd',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pontun',
            name='heimilisfang',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontun',
            name='kennitala',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontun',
            name='land',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontun',
            name='netfang',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontun',
            name='postnumer',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontun',
            name='simanumer',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pontun',
            name='stadur',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
