# Generated by Django 2.0.9 on 2018-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0003_auto_20181009_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontun',
            name='bok',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='baekur', to='baekur.Bok', verbose_name='Bækur'),
        ),
    ]
