# Generated by Django 2.0.9 on 2018-10-07 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0003_auto_20181007_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontun',
            old_name='vidskiptavinur',
            new_name='nafn',
        ),
    ]
