# Generated by Django 2.0.9 on 2018-10-07 22:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0004_auto_20181007_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontun',
            name='athugasemd',
            field=models.TextField(blank=True, verbose_name='Athugasemd'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='buin_til',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Búin til þann'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='heimilisfang',
            field=models.CharField(max_length=255, verbose_name='Heimilisfang'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='kennitala',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\d{6}-\\d{4}$')], verbose_name='Kennitala'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='land',
            field=models.CharField(max_length=255, verbose_name='Land'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='magn',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Magn'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='nafn',
            field=models.CharField(max_length=255, verbose_name='Nafn'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='netfang',
            field=models.EmailField(max_length=254, verbose_name='Netfang'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='postnumer',
            field=models.CharField(max_length=255, verbose_name='Póstnúmer'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='simanumer',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Símanúmer'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='stada',
            field=models.CharField(choices=[('EKKI_AFGREIDD', 'Ekki afgreidd'), ('INNHEIMTA_SEND', 'Innheimta send í heimabanka'), ('AFGREIDD', 'Afgreidd')], default='EKKI_AFGREIDD', max_length=255, verbose_name='Staða'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='stadur',
            field=models.CharField(max_length=255, verbose_name='Staður'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='uppfaerd',
            field=models.DateTimeField(auto_now=True, verbose_name='Uppfærð þann'),
        ),
    ]
