# Generated by Django 2.0.9 on 2018-10-07 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0005_auto_20181007_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontun',
            name='bok',
            field=models.CharField(default='a', max_length=255, verbose_name='Bók'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pontun',
            name='kennitala',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^\\d{10}$')], verbose_name='Kennitala'),
        ),
    ]
