# Generated by Django 2.0.9 on 2018-10-09 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0006_auto_20181009_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontun',
            name='magn',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Magn'),
        ),
    ]
