# Generated by Django 2.0.9 on 2018-10-08 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0006_auto_20181007_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontun',
            name='kennitala',
            field=models.CharField(help_text='Skrifaðu kennitöluna á forminu XXXXXX-XXXX.', max_length=255, validators=[django.core.validators.RegexValidator('^\\d{6}-\\d{4}$')], verbose_name='Kennitala'),
        ),
        migrations.AlterField(
            model_name='pontun',
            name='simanumer',
            field=models.CharField(max_length=255, verbose_name='Símanúmer'),
        ),
    ]
