# Generated by Django 2.0.9 on 2018-10-11 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0008_auto_20181009_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontun',
            name='bok',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pantanir', to='baekur.Bok', verbose_name='Bók'),
        ),
    ]
