# Generated by Django 2.0.9 on 2019-01-15 00:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantanir', '0009_auto_20181011_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontun',
            name='magn',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Fjöldi bókaknippa'),
        ),
    ]
